services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bookmarkuser
      POSTGRES_PASSWORD: bookmarkuser123
      POSTGRES_DB: bookmarks_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookmarkuser -d bookmarks_db"]
      interval: 5s
      retries: 5

  web:
    # 1. CHANGED: Swapped ':latest' for '${IMAGE_TAG}' with a fallback
    image: ghcr.io/palthimalleswari/ci-cd-pipeline:${IMAGE_TAG:-latest}
    command: python manage.py runserver 0.0.0.0:8000
    # 2. REMOVED: Volumes mapping (.-:/app) should be removed in production CD pipelines
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: django-insecure-2y1v&1*xl_)hsln%p86d@d(#_#ix)-77o_0^owf&t-&ggp1qjc
      DEBUG: "1"
      DATABASE_URL: postgres://bookmarkuser:bookmarkuser123@db:5432/bookmarks_db
      ALLOWED_HOSTS: localhost,127.0.0.1
      POSTGRES_DB: bookmarks_db
      POSTGRES_USER: bookmarkuser
      POSTGRES_PASSWORD: bookmarkuser123
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
